name: workshop_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  cupertino_icons: ^1.0.2
  transparent_image: ^2.0.0
  flutter_html: ^2.2.1
  flutter_login: ^4.0.0
  crypto: ^3.0.2
  json_serializable: ^6.5.4
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  equatable: ^2.0.5

dev_dependencies:
  build_runner:
  test:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
